name: "test"

on: [push, pull_request]

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit", "luajit-openresty"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@master
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@master

    - name: build
      run: |
        docker build -t pgmoon-test .

    - name: test
      run: |
        docker run pgmoon-test


